"""empty message

Revision ID: 34e8e57b9ffb
Revises: 52d1eb0b0dc4
Create Date: 2024-09-06 10:44:36.956546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34e8e57b9ffb'
down_revision = '52d1eb0b0dc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('website', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('primary_court', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('play_type', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_column('play_type')
        batch_op.drop_column('primary_court')
        batch_op.drop_column('website')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
